# Use a base image
FROM python:3.12.7-bullseye

# Set the working directory
WORKDIR /app

# Copy requirements first for caching
COPY requirements.txt /app/

# Install dependencies
RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
    software-properties-common \
    apt-utils \
    curl \
    libgomp1 \
    python3-launchpadlib \
    openjdk-11-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set environment variables for Java
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
ENV PATH=$PATH:$JAVA_HOME/bin

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app

# Expose the required port
EXPOSE 9001

# Command to run the socket server
CMD ["python", "socket_server.py"]
